---
name: epp
channels: [conda-forge, nodefaults]
dependencies:
  - jupyter
  - line_profiler
  - matplotlib
  - nlopt
  - numba
  - numpy
  - openpyxl
  - optimagic
  - pandas >= 2.1
  - pip
  - plotly
  - pre-commit
  - pyarrow >= 13.0
  - pytask >= 0.4
  - pytest
  - python==3.12
  - python-kaleido >= 1.0
  - scikit-learn
  - scipy
  - seaborn
  - snakeviz
  - statsmodels
  - toml
  - pip: [pdbp]
